---
engines:
  cppcheck:
    enabled: true
    exclude_patterns:
      - "*Cppcheck does not need standard library headers to get proper results.*"

exclude_paths:
  - "benchmarks/**"
  - "cmake/**"
  - "docs/**"
  - "examples/**"
  - "tests/**"
  - "third-party/**"
  - "**.md"
  - "**.sh"